### ISSUE TITLE
support non-slice based APIs

### ISSUE THREAD

**Issue by jyn514** [RazrFalcon/memmap2-rs#117]
currently, `Mmap` and `MmapMut` expose the following APIs:
![image](https://github.com/RazrFalcon/memmap2-rs/assets/23638587/899eda96-abbf-4a4d-a703-629d06e92c90)

in effect, the only way to read or write the underlying data is by going through a slice. this is convenient, but it means writing concurrently from multiple processes is UB - and indeed, memmap2 has a warning about that in the top-level docs:
> All file-backed memory map constructors are marked unsafe because of the potential for Undefined Behavior (UB) using the map if the underlying file is subsequently modified, in or out of process.

there is no intrinsic reason concurrent modification has to be UB. using atomic operations on the memory should be sufficient - it's still the application's responsibility to prevent data races, but it's at least possible to do, unlike today (because calling `mmap.as_ptr()` implicitly creates a slice, which is UB in the presence of concurrent writes).

---

if `Mmap` had `as_ptr()` and `as_mut_ptr()` functions, it would enable concurrent writes without breaking changes to the slice api. i'm happy to submit a PR if you're interested.

**Comment by adamreichold** [comment]
I think you could just base alternative access strategies on [`MmapRaw`](https://docs.rs/memmap2/latest/memmap2/struct.MmapRaw.html) which would also have the benefit of removing the now unsound slice access methods.

When creating an instance of `Mmap` or `MmapMut`, you are basically promising that slice access is sound due to the environment in which you use these types. Hence your approach would requiring wrapping those to produce a sound API without the slice access in any case. Wrapping a `MmapRaw` appears simpler IMHO.

**Comment by jyn514** [comment]
i didn't see MmapRaw! yes, that's exactly what i wanted, thank you :)
