### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/memmap2-rs#124]
Due to various reasons I will no longer be able to maintain this project. This includes even minor staff like accepting PRs and pushing releases.
Therefore I would like to transfer ownership to someone else. This includes giving an access to this repo + cargo package.
This should be a better choice than simply archiving it and repeating the original `memmap-rs` project history.

@adamreichold would you be interested in maintaining this project?

**Comment by adamreichold** [comment]
Uff. If the alternative is to archive, then yes, I will try to keep the lights on. I am rather stretched myself (I basically had to give up on PyO3 and rust-numpy for a while now.), but I guess merging PR and pushing releases should be possible as the crate is still smallish.

Personally, I think this functionality is foundational enough that we should eventually aim for group maintainership, e.g. transfer this to the rust-lang organisation or something like that.

In any case, I would like to thank you for taking care of this part of the ecosystem for so long! I wish you all the best for whatever lies ahead.

**Comment by RazrFalcon** [comment]
I'm thinking about asking on r/rust as well. Maybe someone would be willing to maintain is as well.
But since the crate has 72M downloads I don't want to give it to random people due to security concerns.

**Comment by laurmaedje** [comment]
Considering that even [rustc itself](https://github.com/rust-lang/rust/blob/a0c2aba29aa9ea50a7c45c3391dd446f856bef7b/compiler/rustc_data_structures/Cargo.toml#L51) depends on this crate, having it rust-lang does not seem that far fetched indeed.

**Comment by tbu-** [comment]
I'd also be up for it. But it seems there are already others who'd be up for it, as well.

**Comment by the8472** [comment]
I'll raise the issue at rust-lang if there's interest.

**Comment by YesSeri** [comment]
I would be able to help, I have quite a bit of free time, and would love to get involved.

**Comment by ultimaweapon** [comment]
If all you want is keep it in the current state without additional features I can help with this. I was an experienced C/C++ developer that moved to Rust so I'm comfortable with low-level things like this.

**Comment by Stetsed** [comment]
As this is a crate directly depended on by Rustc as @laurmaedje mentioned , I think if it is transfered it would make sense to go into rust-lang. If it's not I do think it makes sense to have some sort of verification process in the terms of identity not just a GitHub User, I am not able to offer support for the actual development(As I am still pretty new to rust), but as we saw with the entire xz situtation it can be dangerous.

I will say, I think publicly announcing this, on the r/rust sub aswell does make sense, instead of XZ where it was more in the background just a shift. I hope you are able to find somebody to take over maintenace for the package in a safe way.

Even if it doesn't head into rust-lang I do think @adamreichold recommendation of group maintainership makes sense, as you can have a policy where merge requires >= X maintainers to approve, as it is a pretty finished project this shouldn't cause major development issues but could make the bar higher for potentional malicious input.

I hope you are doing okay, and good luck on you're continued life journey wherever that ends up leading, thank you for the development you have done :saluting_face: .

**Comment by Stipulations** [comment]
Hello, i would be willing to help maintain it and i am willing to verify my identity with the respective groups/authorities.

**Comment by de-vri-es** [comment]
I'll throw my hat in the ring. I already maintain a few crates with varying degrees of popularity. The most downloaded one is [git-version](https://crates.io/crates/git-version), which I co-maintain with Mara Bos (@m-ou-se).

I also maintain a bunch of crates that are basically safe interfaces to libc functionality: [memfile](https://crates.io/crates/memfile), [tokio-seqpacket](https://crates.io/crates/tokio-seqpacket) and [serial2](https://crates.io/crates/serial2) (and accompanying [serial2-tokio](https://crates.io/crates/serial2-tokio)).

**Comment by RazrFalcon** [comment]
Ok, after some considerations I've ended up with: @allan2, @tbu- and @de-vri-es
No particular reasons behind this design. 

I don't think you would have to do anything with this crate in the near feature. All I wish is too keep the lights on with minimal changes to the codebase.

Many thanks to everyone who responded.
