### ISSUE TITLE
Does `lock` require `&mut self`?

### ISSUE THREAD

**Issue by timvisee** [RazrFalcon/memmap2-rs#74]
Is there a good reason for [`lock()`](https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html#method.lock) to require `&mut self`?

To compare, [`advice()`](https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html#method.advise) is just `&self`.

**Comment by adamreichold** [comment]
I think this is a bug as there should be no external synchronization requirements, c.f. e.g. [here](https://stackoverflow.com/questions/38128769/mlock-and-threading). It also delegates to an internal method taking `&self`.

Would you mind creating a PR?

**Comment by timvisee** [comment]
Will do.

**Comment by RazrFalcon** [comment]
Interesting. @adamreichold shouldn't we make those methods `&mut` instead? We're mutating the memory map handle content after all, sort of.

**Comment by adamreichold** [comment]
What we are mutating is the page tables maintained by the operating system. Those are internally synchronized by the kernel (e.g. Linux's infamous `mmap_sem`) and hence POSIX mandates that `mlock` is safe to call from multiple threads.

This is similar to why for example [`File::set_len`](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.set_len) takes `&self` even though it definitely modifies the underlying file. The shared mutable state, i.e. the file system, is synchronized internally via the operating system. And this is strictly necessarily the case as this particular state is shared with other processes and the kernel cannot allow one process to introduce data races into another.

This synchronization is also the reason why heavily multi-threaded programs on Linux suffer when a lot of `mmap` operations are involved, because those are always serialised by `mmap_sem`.

**Comment by adamreichold** [comment]
(There is even talk about sharing not only pages but also page tables between processes for reasons of efficiency for heavily containerized systems so that `mlock` in one process would affect the mapping in all other processes sharing it, c.f. https://lwn.net/Articles/895217/)

**Comment by timvisee** [comment]
Thanks for the quick response & merge. :smile:

**Comment by timvisee** [comment]
@RazrFalcon Would you mind to push this to `crates.io` in the upcoming days?

**Comment by RazrFalcon** [comment]
Done.
